apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-deployment
  labels:
    app: nginx-hello
    type: front-end
  namespace: default

spec:
  selector:
      matchLabels:
        app: nginx-hello 
        type: front-end

  template:
    metadata:
      labels:
        app: nginx-hello
        type: front-end
      namespace: default

    spec:
      containers:
        - name: nginx-hello-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent          
          volumeMounts:
            - name: vol-nginx-hello
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always

      volumes:
        - name: vol-nginx-hello 
          persistentVolumeClaim:
            claimName: postgres-pvc
      
  replicas: 1
