apiVersion: v1
kind: Service
metadata:
  name: postgres 
  labels:
    app: postgres
    type: server
spec:
  type: NodePort
  ports:
    - name: pgsql
      port: 5432
      targetPort: 5432
  selector:
    app: postgres 
    type: server