apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-hello-volume-claim-localpath
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path


